### PR TITLE
Proposed minor improvements

### PR DESCRIPTION
**Pull request by manwar**
Hi @oalders 

Please review the PR.
This was assigned to me as November month assignment by Pull Request Club.

Many Thanks.
Best Regards,
Mohammad S Anwar

### CODE REVIEW

**Comment by oalders** [comment]
Thanks @manwar.  I think I understand what you're doing, but it's not clear to my why you're using `our` rather than `my` here.  Having said that, I wonder if we'd be better off using something like `Const::Fast` here, if we were ok with the added dependencies.

**Comment by manwar** [comment]
@oalders there is no particular reason of using "our". I am happy to change to whatever you suggest to.

**Comment by oalders** [comment]
Ok, I've asked for others to comment on this as well, so maybe hold off before making any changes. :)

**Comment by karenetheridge** [comment]
I'm not a fan of changing the use of these strings -- it adds cognitive load to have to keep referring elsewhere in the document to see what these values are.

The defined check is great.

**Comment by manwar** [comment]
@karenetheridge I have removed the changes completely and kept just defined check.
Is this any good?

**Comment by oalders** [comment]
Thanks @manwar!

**Pull request merged**
